// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5xQ-lj3hfINKUJJDtF7OzSsBhMM_0D3o',
    appId: '1:659032381526:web:75e420bfe575c099fa03f7',
    messagingSenderId: '659032381526',
    projectId: 'list-authen',
    authDomain: 'list-authen.firebaseapp.com',
    storageBucket: 'list-authen.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsYe8VtekgHBCiZTFuAp5Q47TadnBVc48',
    appId: '1:659032381526:android:8b7bea61eeda04dafa03f7',
    messagingSenderId: '659032381526',
    projectId: 'list-authen',
    storageBucket: 'list-authen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5fnbaPGv10X1QV0VoqZvyg0vD7EyEiCs',
    appId: '1:659032381526:ios:879871ce815f52edfa03f7',
    messagingSenderId: '659032381526',
    projectId: 'list-authen',
    storageBucket: 'list-authen.firebasestorage.app',
    iosBundleId: 'com.example.groceryListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5fnbaPGv10X1QV0VoqZvyg0vD7EyEiCs',
    appId: '1:659032381526:ios:879871ce815f52edfa03f7',
    messagingSenderId: '659032381526',
    projectId: 'list-authen',
    storageBucket: 'list-authen.firebasestorage.app',
    iosBundleId: 'com.example.groceryListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5xQ-lj3hfINKUJJDtF7OzSsBhMM_0D3o',
    appId: '1:659032381526:web:c6c397b8c6cdbd15fa03f7',
    messagingSenderId: '659032381526',
    projectId: 'list-authen',
    authDomain: 'list-authen.firebaseapp.com',
    storageBucket: 'list-authen.firebasestorage.app',
  );
}
